'''
Created on 2013/9/13

@author: RobertChen
'''
import ctypes
from ctypes import Structure, Union, POINTER, sizeof, byref, c_ushort, c_ubyte, c_uint,c_ulong, c_wchar, create_unicode_buffer
from ctypes.wintypes import BOOL, BOOLEAN, BYTE, \
                            DWORD, HANDLE, HWND, LONG, LPCWSTR, LPVOID, LPWSTR, ULONG, USHORT, WCHAR, WORD
"""
['ATOM', 'BOOL', 'BOOLEAN', 'BYTE', 'COLORREF', 'DOUBLE', 'DWORD', 'FILETIME', 'FLOAT', 'HACCEL', 'HANDLE', 'HBITMAP', 'HBRUSH', 'HCOLORSPACE', 'HDC', 'HDESK', 'HDWP', 'HENHMETAFILE', 'HFONT', 'HGDIOBJ', 'HGLOBAL', 'HHOOK', 'HICON', 'HINSTANCE', 'HKEY', 'HKL', 'HLOCAL', 'HMENU', 'HMETAFILE', 'HMODULE', 'HMONITOR', 'HPALETTE', 'HPEN', 'HRGN', 'HRSRC', 'HSTR', 'HTASK', 'HWINSTA', 'HWND', 'INT', 'LANGID', 'LARGE_INTEGER', 'LCID', 'LCTYPE', 'LGRPID', 'LONG', 'LPARAM', 'LPCOLESTR', 'LPCSTR', 'LPCVOID', 'LPCWSTR', 'LPOLESTR', 'LPSTR', 'LPVOID', 'LPWSTR', 'MAX_PATH', 'MSG', 'OLESTR', 'POINT', 'POINTL', 'RECT', 'RECTL', 'RGB', 'SC_HANDLE', 'SERVICE_STATUS_HANDLE', 'SHORT', 'SIZE', 'SIZEL', 'SMALL_RECT', 'UINT', 'ULARGE_INTEGER', 'ULONG', 'USHORT', 'VARIANT_BOOL', 'WCHAR', 'WIN32_FIND_DATAA', 'WIN32_FIND_DATAW', 'WORD', 'WPARAM', '_COORD', '_FILETIME', '_LARGE_INTEGER', '_POINTL', '_RECTL', '_SMALL_RECT', '_ULARGE_INTEGER', '__builtins__', '__doc__', '__name__', '__package__', 'tagMSG', 'tagPOINT', 'tagRECT', 'tagSIZE']
"""
PVOID = HANDLE 
ULONG_PTR = POINTER(ULONG)
PBYTE = POINTER(BYTE)
PDWORD = POINTER(DWORD)
UCHAR = c_ubyte
ENUM  = c_uint
TCHAR = WCHAR
LPCTSTR = LPCWSTR  
PCTSTR  = LPCWSTR
PTSTR = LPWSTR
HDEVINFO = PVOID
USAGE = c_ushort
INVALID_HANDLE_VALUE = HANDLE(-1)

"""CreateFile parameter"""
GENERIC_READ     = (-2147483648)
GENERIC_WRITE    = (1073741824)
FILE_SHARE_READ  = 1
FILE_SHARE_WRITE = 2
"""dwCreationDisposition"""
CREATE_ALWAYS     = 2
CREATE_NEW        = 1
OPEN_ALWAYS       = 4
OPEN_EXISTING     = 3
TRUNCATE_EXISTING = 5
"""dwFlagsAndAttributes"""
FILE_ATTRIBUTE_ARCHIVE       = 32    #(0x20)
FILE_ATTRIBUTE_ENCRYPTED     = 16384 #(0x4000)
FILE_ATTRIBUTE_HIDDEN        = 2     #(0x2)
FILE_ATTRIBUTE_NORMAL        = 128   #(0x80)
FILE_ATTRIBUTE_OFFLINE       = 4096  #(0x1000)
FILE_ATTRIBUTE_READONLY      = 1     #(0x1)
FILE_ATTRIBUTE_SYSTEM        = 4     #(0x4)
FILE_ATTRIBUTE_TEMPORARY     = 256   #(0x100)
FILE_FLAG_BACKUP_SEMANTICS   = 33554432   #(0x02000000)
FILE_FLAG_DELETE_ON_CLOSE    = 67108864   #(0x04000000)
FILE_FLAG_NO_BUFFERING       = 536870912  #(0x20000000)
FILE_FLAG_OPEN_NO_RECALL     = 1048576    #(0x00100000)
FILE_FLAG_OPEN_REPARSE_POINT = 2097152    #(0x00200000)
FILE_FLAG_OVERLAPPED         = 0x40000000
FILE_FLAG_POSIX_SEMANTICS    = 0x00100000
FILE_FLAG_RANDOM_ACCESS      = 0x10000000
FILE_FLAG_SESSION_AWARE      = 0x00800000
FILE_FLAG_SEQUENTIAL_SCAN    = 0x08000000
FILE_FLAG_WRITE_THROUGH      = 0x80000000