"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import wx
import FrameBase
import MainPanel

# Implementing MainFrame
class MainFrame( FrameBase.MainFrame ):
	def __init__( self, parent ):
		FrameBase.MainFrame.__init__( self, parent )
		self.m_myPanel = MainPanel.MainPanel(self)
		self.GetSizer().Add( self.m_myPanel, 0, wx.ALL, 5 )
		
if __name__=='__main__':
	app = wx.App()
	my_frame = MainFrame(None)
	my_frame.Show()
	app.MainLoop()
	del app