"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import wx
import FrameColor

# Implementing MainFrame
class SettingMainFrame( FrameColor.MainFrame ):
    def __init__( self, parent ):
        FrameColor.MainFrame.__init__( self, parent )


if __name__=='__main__':
    app = wx.App()
    my_frame = SettingMainFrame(None)
    my_frame.Show()
    app.MainLoop()